### ISSUE TITLE
Open Source Prep Checklist

### ISSUE THREAD

**Issue by yosevu** [sparkbox/sparkeats#376]
~- [ ] Heroku: Delete app (Admin)~ Will keep Heroku app for now
~- [ ] Heroku: Check for ClearDB subscription (Admin)~ Will keep Heroku app for now

- [x] Circle: Stop Building project
- [x] GitHub: Delete environments
- [x] GitHub: Delete Webhooks e.g. Zenhub, Atlassian, Slapdash etc.
- [x] GitHub: Delete Code Climate deploy key
- [x] Check for remaining tasks on Heroku, CircleCi and CodeClimate
~~- [ ] GitHub: Remove apps e.g. Slack, Jira (Admin)~~ Unnecessary to open source
- [x] GitHub: Change visibility of the [Open Source Sparkeats ](https://github.com/orgs/sparkbox/projects/1)GitHub project to "Public" (Admin)
